name: Lint & Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node

      - name: (lint commit) check all commits
        uses: wagoid/commitlint-github-action@v4
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules

      - name: validate (lint)
        run: pnpm run lint

      - name: run test
        run: pnpm run test -- --collectCoverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
